### ISSUE TITLE
Support loading a script from *.user.js file

### ISSUE THREAD

**Issue by techygrrrl** [BlackGlory/eternity#17]
Other user script runners have the ability to auto-load a user script into the extension when visiting a `*.user.js` URL. 

Would it be possible to add this feature to this extension?

Right now when I try to do this, I see this error, which is the same error I see when the extension is disabled.

![image](https://github.com/user-attachments/assets/9e1fcba9-04f8-491c-b2de-c0056b72cb70)

**Comment by BlackGlory** [comment]
I'm not really interested in hijacking browser navigation, but the extension does need a way to import scripts.

The most likely option to be implemented would be to load the currently selected text into the editor via the context menu.

**Comment by examosa** [comment]
What about importing from a URL?

**Comment by BlackGlory** [comment]
> What about importing from a URL?

The current UI design needs to be modified to support importing from URLs.
I do not plan to provide a single-page dashboard, so I have to find a way to use the limited space of the popup window.
Perhaps the easiest way is to change all text buttons to icon buttons to free up space.

**Comment by examosa** [comment]
Now that I think about it, importing from a URL is already technically possible using the `@update-url` tag. However, it currently seems to be broken.

To test it, I created a new script with the following content:

```js
// ==UserScript==
// @name Google Translate Auto Languages
// @update-url https://update.greasyfork.org/scripts/378166/Google%20Translate%20Auto%20Languages.user.js
// @match *://translate.google.com/*
// ==UserScript==
```

When clicking the update button from the editor, nothing happens. Same goes for the "Update All Scripts" button from the popup.

I think it's because of the way `applyPropertyDecorators` is being used [here](https://github.com/BlackGlory/eternity/blob/f25f168c3364291bae171a56bfc320d89e0fa16d/src/background/index.ts#L93-L100) which in turn is causing `this` to be `undefined` [here](https://github.com/BlackGlory/eternity/blob/f25f168c3364291bae171a56bfc320d89e0fa16d/src/background/index.ts#L75) at runtime.

**Comment by BlackGlory** [comment]
@examosa 
Just updated the code, should fix it.
In the latest version, invalid scripts can be downloaded and saved. The extension lacks a good way to tell the user that the script is invalid.

**Comment by examosa** [comment]
I was still unable to update from the URL with the latest changes; I got it working locally by making the following change:

```diff
diff --git a/src/background/index.ts b/src/background/index.ts
index 1c5a576..8ba406d 100644
--- a/src/background/index.ts
+++ b/src/background/index.ts
@@ -90,14 +90,7 @@ createServer<IBackgroundAPI>(
   applyPropertyDecorators(
     api
   , Object.keys(api) as Array<keyof IBackgroundAPI>
-  , (fn: (...args: unknown[]) => unknown) => {
-      return async function (this: typeof api, ...args: unknown[]): Promise<unknown> {
-        // 等待初始化/迁移执行完毕
-        await launched
-
-        return await Reflect.apply(fn, this, args)
-      }
-    }
+  , (fn: (...args: unknown[]) => unknown) => (...args: unknown[]) => launched.then(fn.bind(api, ...args))
   ) as ImplementationOf<IBackgroundAPI>
 )
```

**Comment by BlackGlory** [comment]
I may be too tired, but they should be equivalent code.
The only difference is that the first code uses `this` and the second code directly passes in the `api` object.
Did you modify other parts of the code?

**Comment by examosa** [comment]
As originally written, the code is using a [`this` parameter](https://www.typescriptlang.org/docs/handbook/2/classes.html#this-parameters) which only carries type information; the actual value of `this` still winds up as `undefined` at runtime because the `async function` is defined _inside_ an arrow function where `this` is [lexically bound](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#arrow_functions). So each `fn` of `api` either has to be explicitly bound to `api` when invoked, or already bound to `api` before using `applyPropertyDecorators` e.g. with [`bind`](https://github.com/BlackGlory/extra-proxy/blob/08d9a709e5380bdea37da73af03d42c0063ed604/src/bind.ts) from your `extra-proxy` lib.

A smaller change to the same effect:

```diff
diff --git a/src/background/index.ts b/src/background/index.ts
index 1c5a576..39800a9 100644
--- a/src/background/index.ts
+++ b/src/background/index.ts
@@ -91,11 +91,11 @@ createServer<IBackgroundAPI>(
     api
   , Object.keys(api) as Array<keyof IBackgroundAPI>
   , (fn: (...args: unknown[]) => unknown) => {
-      return async function (this: typeof api, ...args: unknown[]): Promise<unknown> {
+      return async function (...args: unknown[]): Promise<unknown> {
         // 等待初始化/迁移执行完毕
         await launched
 
-        return await Reflect.apply(fn, this, args)
+        return await Reflect.apply(fn, api, args) // fn.apply(api, args) would also work
       }
     }
   ) as ImplementationOf<IBackgroundAPI>
```

It might also be a good idea to update `applyPropertyDecorators` to forward the `this` binding of [`value`](https://github.com/BlackGlory/extra-proxy/blob/08d9a709e5380bdea37da73af03d42c0063ed604/src/decorator.ts#L15) if it's a function; it could either pass `obj` as a second argument to `propertyDecorator` or invoke it using [`Function.prototype.call`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call).

**Comment by BlackGlory** [comment]
@examosa Sadly, you are wrong. `applyPropertyDecorators` was actually designed with tests specifically for this use case, which you can find here: <https://github.com/BlackGlory/extra-proxy/blob/master/__tests__/decorator.spec.ts>, and the `this` in this code doesn't work the way you think, I don't want to give a JavaScript lecture here.

The real question is why the code that works in my browser doesn't work in yours.

**Comment by examosa** [comment]
Ah, you're right! I must have forgotten to reload the extension after rebuilding the first time 😅

**Comment by Xdy1579883916** [comment]
@examosa 

Although eternity uses a Meta similar to Greasemonkey, it does not fully support Greasemonkey's script Meta


Thanks to @BlackGlory for open source. [vanilla-pudding](https://github.com/Xdy1579883916/vanilla-pudding) borrows the idea and Code of ​​`eternity`. You are welcome to try it.

1. First you need to create a new script, paste Meta in the editor, and save it（CTRL + S）
![image](https://github.com/user-attachments/assets/9ea760b6-caa8-41c4-b643-3d5b78e8bc08)

2. Refresh the editor page and you will find that the plugin is automatically converted into a compliant Meta
![image](https://github.com/user-attachments/assets/94ca569f-2f0e-4f7d-8106-da371ca071aa)

3. Yes. Next, we need to click Update, and the plugin will update the script content according to the `@update-url` address. Refresh the editor page to see the updated source code.
![image](https://github.com/user-attachments/assets/2e3b3a56-aca5-4f37-b6cb-9544e0ee80c6)

I tested your script and it works fine on the Google Translate page ~
